### ISSUE TITLE
Issue for mailer

### ISSUE THREAD

**Issue by talset** [redhat-cip/rcip-openshift-ansible#43]
```
/usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:80:in `api_request': api.json settings not found. (RuntimeError)
    from /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:123:in `stash_exists?'
    from /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:135:in `block (2 levels) in filter_silenced'
    from /usr/share/ruby/timeout.rb:66:in `timeout'
    from /usr/share/ruby/timeout.rb:97:in `timeout'
    from /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced'
    from /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:132:in `each'
    from /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:132:in `filter_silenced'
    from /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:31:in `filter'
    from /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:54:in `block in <class:Handler>'
```

**Comment by talset** [comment]
Log in sensu

```
{"timestamp":"2016-05-02T18:20:39.079861+0200","level":"info","message":"handler output","handler":{"type":"pipe","command":"/usr/local/bin/handler-mailer.rb","name":"mailer"},"output":["/usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:80:in `api_request': api.json settings not found. (RuntimeError)\n","\tfrom /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:123:in `stash_exists?'\n","\tfrom /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:135:in `block (2 levels) in filter_silenced'\n","\tfrom /usr/share/ruby/timeout.rb:66:in `timeout'\n","\tfrom /usr/share/ruby/timeout.rb:97:in `timeout'\n","\tfrom /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced'\n","\tfrom /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:132:in `each'\n","\tfrom /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:132:in `filter_silenced'\n","\tfrom /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:31:in `filter'\n","\tfrom /usr/local/share/gems/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:54:in `block in <class:Handler>'\n"]}
```

**Comment by talset** [comment]
b412c8320d38b799fdd90ae5bfb562601c8cdaa8
